### ISSUE TITLE
Investigate moving to Fastify for the HTTP server

### ISSUE THREAD

**Issue by boudra** [gitcoinco/allo-indexer#67]
While writing a catch all error handler for the API I noticed express is quite outdated and doesn't handle Promise rejections at all, only synchronous exceptions.

I had to use https://www.npmjs.com/package/express-async-errors which is not ideal, I feel this is something an HTTP server should have by default and I wonder what else we'll have issues with.

Fastify seems to do it properly and is built with a modern stack in mind: https://www.fastify.io/docs/latest/Reference/Errors/

**Comment by boudra** [comment]
any thoughts here @vacekj @gravityblast @hmrtn ?

**Comment by vacekj** [comment]
Down, easy transition.

**Comment by bard** [comment]
If this is only about async errors, I'd say let's not worry, `express-async-errors` has been working fine for me for ages, and Express 4 is still the easiest experience for contributors because it's what they're most likely already familiar with. (In fact, I still use it over Express 5, which has async error handling built in, for that reason.)

However, if Express 4 is falling short on other fronts, by all means let's look at that and see if we need to migrate away from it.
